name: CI

on:
  workflow_dispatch:
  push:
  pull_request:


defaults:
  run:
    shell: bash -l {0}


jobs:
  test_with_conda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: dev-env.yml
          environment-name: dev-env
          init-shell: >-
            bash

      - name: Install Playwright
        shell: bash -el {0}
        run: |
          playwright install

      - name: Install pyjs-code-runner
        shell: bash -el {0}
        run: |
          python -m pip install . --no-deps

      - name: Run Tests
        shell: bash -el {0}
        run: |
          pytest -s -vvv 


  test_with_pip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: dev-env-pip.yml
          environment-name: dev-env

      - name: Install pyjs-code-runner
        shell: bash -el {0}
        run: |
          python -m pip install .
          playwright install

      - name: Run Tests
        shell: bash -el {0}
        run: |
          pytest -s -vvv 
